#!/usr/bin/env bash

source ~/.bash_profile

# Check if dart is available
if command -v dart &> /dev/null
then
	DART_COMMAND="dart"
else
	echo "Error: Failed to find dart in your path"
	exit 1
fi

# dart fix only supports single files or folders, so we need to loop over each one
# individually.
FIX_EXIT_CODE=0
for FILE in $@
do
  output=$(eval "dart fix --apply $FILE")
  if [[ $output != *"Nothing to fix"* ]]; then
    FIX_EXIT_CODE=1
  fi
done


if [[ FIX_EXIT_CODE -ne 0 ]]; then
  exit 1
fi

